"""Add month to recurring rules

Revision ID: 1ba37b0a7e8b
Revises: 4280390631eb
Create Date: 2025-09-18 12:09:11.535395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba37b0a7e8b'
down_revision: Union[str, Sequence[str], None] = '4280390631eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reglas_recurrentes', sa.Column('mes', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transacciones_estado'), 'transacciones', ['estado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transacciones_estado'), table_name='transacciones')
    op.drop_column('reglas_recurrentes', 'mes')
    # ### end Alembic commands ###
