"""add fastapi-users auth fields to Usuario

Revision ID: 29c02c7a9239
Revises: f9b1b5966d82
Create Date: 2025-07-26 09:59:54.435164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29c02c7a9239'
down_revision: Union[str, Sequence[str], None] = 'f9b1b5966d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('usuarios', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('usuarios', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'is_superuser')
    op.drop_column('usuarios', 'is_verified')
    op.drop_column('usuarios', 'is_active')
    # ### end Alembic commands ###
