"""Add is_active to recurring rules

Revision ID: 8f936f88e11b
Revises: 0001_create_base_tables
Create Date: 2025-11-13 15:18:05.903672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f936f88e11b'
down_revision: Union[str, Sequence[str], None] = '0001_create_base_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reglas_recurrentes', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reglas_recurrentes', 'is_active')
    # ### end Alembic commands ###
